-- create database

-- CREATE DATABASE ${DB_NAME:time_reporting_db};

-- create user and grant privileges

-- CREATE USER ${DB_USER:time_reporting_app} WITH PASSWORD '${DB_PASSWORD:secret}';

-- GRANT CONNECT ON DATABASE ${DB_NAME:time_reporting_db} TO ${DB_USER:time_reporting_app};

-- GRANT USAGE ON SCHEMA public TO ${DB_USER:time_reporting_app};

-- GRANT SELECT, INSERT, UPDATE, DELETE
-- ON ALL TABLES IN SCHEMA public
-- TO ${DB_USER:time_reporting_app};

-- ALTER DEFAULT PRIVILEGES IN SCHEMA public
-- GRANT SELECT, INSERT, UPDATE, DELETE
-- ON TABLES
-- TO ${DB_USER:time_reporting_app};

-- create tables

CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    user_role VARCHAR(50) NOT NULL CHECK (user_role IN ('REGULAR', 'MANAGER'))
);

CREATE TABLE activity (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    parentActivity BIGINT REFERENCES activity(id)
);

CREATE TABLE time_report (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    activity_id BIGINT NOT NULL REFERENCES activity(id),
    date DATE NOT NULL,
    duration INTERVAL NOT NULL,
    date_reported DATE NOT NULL
);