apiVersion: apps/v1
kind: Deployment
metadata:
  name: tra-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tra-backend
  template:
    metadata:
      labels:
        app: tra-backend
    spec:
      containers:
        - name: tra-backend
          image: tra-backend:0.0.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: tra-backend-config
            - secretRef:
                name: tra-backend-secrets