spring.application.name=timereportingapp

# JDBC
spring.datasource.url=jdbc:postgresql://localhost:5432/time_reporting
spring.datasource.username=time_reporting_app
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=true
spring.sql.init.mode=always
spring.sql.init.platform=postgres

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect